export const dataHooks = {
    TODO_INPUT : 'TODO_INPUT',
    ADD_BTN:'ADD_BTN',
    TODO_ITEM:'TODO_ITEM',
    TODO_ITEM_DONE:'TODO_ITEM_DONE',
    TODO_ITEM_EDIT:'TODO_ITEM_EDIT',
    TODO_ITEM_DELETE:'TODO_ITEM_DELETE',
    TODO_ITEM_EDIT_INPUT:'TODO_ITEM_EDIT_INPUT',
    TODO_ITEM_CONTENT:'TODO_ITEM_CONTENT'
}